SPECIAL_MODELS: dict[str, str] = {
    "minecraft:item/chest": "minecraft:chest",
    "minecraft:item/conduit": "minecraft:conduit",
    "minecraft:item/creeper_head": "minecraft:head",
    "minecraft:item/decorated_pot": "minecraft:decorated_pot",
    "minecraft:item/dragon_head": "minecraft:head",
    "minecraft:item/ender_chest": "minecraft:chest",
    "minecraft:item/piglin_head": "minecraft:head",
    "minecraft:item/player_head": "minecraft:head",
    "minecraft:item/shield": "minecraft:shield",
    "minecraft:item/shulker_box": "minecraft:shulker_box",
    "minecraft:item/skeleton_skull": "minecraft:head",
    "minecraft:item/trapped_chest": "minecraft:chest",
    "minecraft:item/trident": "minecraft:trident",
    "minecraft:item/wither_skeleton_skull": "minecraft:head",
    "minecraft:item/zombie_head": "minecraft:head",

    "minecraft:item/black_banner": "minecraft:banner",
    "minecraft:item/blue_banner": "minecraft:banner",
    "minecraft:item/brown_banner": "minecraft:banner",
    "minecraft:item/cyan_banner": "minecraft:banner",
    "minecraft:item/gray_banner": "minecraft:banner",
    "minecraft:item/green_banner": "minecraft:banner",
    "minecraft:item/light_blue_banner": "minecraft:banner",
    "minecraft:item/light_gray_banner": "minecraft:banner",
    "minecraft:item/lime_banner": "minecraft:banner",
    "minecraft:item/magenta_banner": "minecraft:banner",
    "minecraft:item/orange_banner": "minecraft:banner",
    "minecraft:item/pink_banner": "minecraft:banner",
    "minecraft:item/purple_banner": "minecraft:banner",
    "minecraft:item/red_banner": "minecraft:banner",
    "minecraft:item/white_banner": "minecraft:banner",
    "minecraft:item/yellow_banner": "minecraft:banner",

    "minecraft:item/black_bed": "minecraft:bed",
    "minecraft:item/blue_bed": "minecraft:bed",
    "minecraft:item/brown_bed": "minecraft:bed",
    "minecraft:item/cyan_bed": "minecraft:bed",
    "minecraft:item/gray_bed": "minecraft:bed",
    "minecraft:item/green_bed": "minecraft:bed",
    "minecraft:item/light_blue_bed": "minecraft:bed",
    "minecraft:item/light_gray_bed": "minecraft:bed",
    "minecraft:item/lime_bed": "minecraft:bed",
    "minecraft:item/magenta_bed": "minecraft:bed",
    "minecraft:item/orange_bed": "minecraft:bed",
    "minecraft:item/pink_bed": "minecraft:bed",
    "minecraft:item/purple_bed": "minecraft:bed",
    "minecraft:item/red_bed": "minecraft:bed",
    "minecraft:item/white_bed": "minecraft:bed",
    "minecraft:item/yellow_bed": "minecraft:bed",

    "minecraft:item/black_shulker_box": "minecraft:shulker_box",
    "minecraft:item/blue_shulker_box": "minecraft:shulker_box",
    "minecraft:item/brown_shulker_box": "minecraft:shulker_box",
    "minecraft:item/cyan_shulker_box": "minecraft:shulker_box",
    "minecraft:item/gray_shulker_box": "minecraft:shulker_box",
    "minecraft:item/green_shulker_box": "minecraft:shulker_box",
    "minecraft:item/light_blue_shulker_box": "minecraft:shulker_box",
    "minecraft:item/light_gray_shulker_box": "minecraft:shulker_box",
    "minecraft:item/lime_shulker_box": "minecraft:shulker_box",
    "minecraft:item/magenta_shulker_box": "minecraft:shulker_box",
    "minecraft:item/orange_shulker_box": "minecraft:shulker_box",
    "minecraft:item/pink_shulker_box": "minecraft:shulker_box",
    "minecraft:item/purple_shulker_box": "minecraft:shulker_box",
    "minecraft:item/red_shulker_box": "minecraft:shulker_box",
    "minecraft:item/white_shulker_box": "minecraft:shulker_box",
    "minecraft:item/yellow_shulker_box": "minecraft:shulker_box",
}



TINT_DATA: dict[str, list[dict]] = {
    "minecraft:item/acacia_leaves": [{"type": "minecraft:constant", "value": -12012264}], 
    "minecraft:item/allay_spawn_egg": [{"type": "minecraft:constant", "value": -16721153}, {"type": "minecraft:constant", "value": -16732673}], 
    "minecraft:item/armadillo_spawn_egg": [{"type": "minecraft:constant", "value": -5410451}, {"type": "minecraft:constant", "value": -8239032}], 
    "minecraft:item/axolotl_spawn_egg": [{"type": "minecraft:constant", "value": -278045}, {"type": "minecraft:constant", "value": -5886604}], 
    "minecraft:item/bat_spawn_egg": [{"type": "minecraft:constant", "value": -11780560}, {"type": "minecraft:constant", "value": -15790321}], 
    "minecraft:item/bee_spawn_egg": [{"type": "minecraft:constant", "value": -1195197}, {"type": "minecraft:constant", "value": -12377061}], 
    "minecraft:item/birch_leaves": [{"type": "minecraft:constant", "value": -8345771}], 
    "minecraft:item/blaze_spawn_egg": [{"type": "minecraft:constant", "value": -609791}, {"type": "minecraft:constant", "value": -1922}], 
    "minecraft:item/bogged_spawn_egg": [{"type": "minecraft:constant", "value": -7693198}, {"type": "minecraft:constant", "value": -13546213}], 
    "minecraft:item/breeze_spawn_egg": [{"type": "minecraft:constant", "value": -5270305}, {"type": "minecraft:constant", "value": -7248161}], 
    "minecraft:item/camel_spawn_egg": [{"type": "minecraft:constant", "value": -212119}, {"type": "minecraft:constant", "value": -3435721}], 
    "minecraft:item/cat_spawn_egg": [{"type": "minecraft:constant", "value": -1062770}, {"type": "minecraft:constant", "value": -6983082}], 
    "minecraft:item/cave_spider_spawn_egg": [{"type": "minecraft:constant", "value": -15973810}, {"type": "minecraft:constant", "value": -5763570}], 
    "minecraft:item/chicken_spawn_egg": [{"type": "minecraft:constant", "value": -6184543}, {"type": "minecraft:constant", "value": -65536}], 
    "minecraft:item/cod_spawn_egg": [{"type": "minecraft:constant", "value": -4085910}, {"type": "minecraft:constant", "value": -1719157}], 
    "minecraft:item/cow_spawn_egg": [{"type": "minecraft:constant", "value": -12306906}, {"type": "minecraft:constant", "value": -6184543}], 
    "minecraft:item/creaking_spawn_egg": [{"type": "minecraft:constant", "value": -10526881}, {"type": "minecraft:constant", "value": -231406}], 
    "minecraft:item/creeper_spawn_egg": [{"type": "minecraft:constant", "value": -15882485}, {"type": "minecraft:constant", "value": -16777216}], 
    "minecraft:item/dark_oak_leaves": [{"type": "minecraft:constant", "value": -12012264}], 
    "minecraft:item/dolphin_spawn_egg": [{"type": "minecraft:constant", "value": -14533811}, {"type": "minecraft:constant", "value": -394759}], 
    "minecraft:item/donkey_spawn_egg": [{"type": "minecraft:constant", "value": -11320007}, {"type": "minecraft:constant", "value": -7965338}], 
    "minecraft:item/drowned_spawn_egg": [{"type": "minecraft:constant", "value": -7343657}, {"type": "minecraft:constant", "value": -8807323}], 
    "minecraft:item/elder_guardian_spawn_egg": [{"type": "minecraft:constant", "value": -3224390}, {"type": "minecraft:constant", "value": -9144685}], 
    "minecraft:item/enderman_spawn_egg": [{"type": "minecraft:constant", "value": -15329770}, {"type": "minecraft:constant", "value": -16777216}], 
    "minecraft:item/endermite_spawn_egg": [{"type": "minecraft:constant", "value": -15329770}, {"type": "minecraft:constant", "value": -9539986}], 
    "minecraft:item/ender_dragon_spawn_egg": [{"type": "minecraft:constant", "value": -14935012}, {"type": "minecraft:constant", "value": -2065926}], 
    "minecraft:item/evoker_spawn_egg": [{"type": "minecraft:constant", "value": -6972517}, {"type": "minecraft:constant", "value": -14803942}], 
    "minecraft:item/fern": [{"type": "minecraft:grass", "downfall": 1.0, "temperature": 0.5}], 
    "minecraft:item/filled_map": [{"type": "minecraft:constant", "value": -1}, {"type": "minecraft:map_color", "default": 4603950}], 
    "minecraft:item/firework_star": [{"type": "minecraft:constant", "value": -1}, {"type": "minecraft:firework", "default": -7697782}], 
    "minecraft:item/fox_spawn_egg": [{"type": "minecraft:constant", "value": -2771297}, {"type": "minecraft:constant", "value": -3380960}], 
    "minecraft:item/frog_spawn_egg": [{"type": "minecraft:constant", "value": -3115964}, {"type": "minecraft:constant", "value": -14468}], 
    "minecraft:item/ghast_spawn_egg": [{"type": "minecraft:constant", "value": -394759}, {"type": "minecraft:constant", "value": -4408132}], 
    "minecraft:item/glow_squid_spawn_egg": [{"type": "minecraft:constant", "value": -16165290}, {"type": "minecraft:constant", "value": -7999044}], 
    "minecraft:item/goat_spawn_egg": [{"type": "minecraft:constant", "value": -5925764}, {"type": "minecraft:constant", "value": -11187906}], 
    "minecraft:item/grass_block": [{"type": "minecraft:grass", "downfall": 1.0, "temperature": 0.5}], 
    "minecraft:item/guardian_spawn_egg": [{"type": "minecraft:constant", "value": -10845582}, {"type": "minecraft:constant", "value": -950992}], 
    "minecraft:item/hoglin_spawn_egg": [{"type": "minecraft:constant", "value": -3772843}, {"type": "minecraft:constant", "value": -10525596}], 
    "minecraft:item/horse_spawn_egg": [{"type": "minecraft:constant", "value": -4153731}, {"type": "minecraft:constant", "value": -1121024}], 
    "minecraft:item/husk_spawn_egg": [{"type": "minecraft:constant", "value": -8818591}, {"type": "minecraft:constant", "value": -1651564}], 
    "minecraft:item/iron_golem_spawn_egg": [{"type": "minecraft:constant", "value": -2372158}, {"type": "minecraft:constant", "value": -9133262}], 
    "minecraft:item/jungle_leaves": [{"type": "minecraft:constant", "value": -12012264}], 
    "minecraft:item/large_fern": [{"type": "minecraft:grass", "downfall": 1.0, "temperature": 0.5}], 
    "minecraft:item/leather_horse_armor": [{"type": "minecraft:dye", "default": -6265536}], 
    "minecraft:item/lily_pad": [{"type": "minecraft:constant", "value": -9321636}], 
    "minecraft:item/lingering_potion": [{"type": "minecraft:potion", "default": -13083194}], 
    "minecraft:item/llama_spawn_egg": [{"type": "minecraft:constant", "value": -4153731}, {"type": "minecraft:constant", "value": -6725824}], 
    "minecraft:item/magma_cube_spawn_egg": [{"type": "minecraft:constant", "value": -13369344}, {"type": "minecraft:constant", "value": -197632}], 
    "minecraft:item/mangrove_leaves": [{"type": "minecraft:constant", "value": -7158200}], 
    "minecraft:item/mooshroom_spawn_egg": [{"type": "minecraft:constant", "value": -6287600}, {"type": "minecraft:constant", "value": -4737097}], 
    "minecraft:item/mule_spawn_egg": [{"type": "minecraft:constant", "value": -15007232}, {"type": "minecraft:constant", "value": -11455715}], 
    "minecraft:item/oak_leaves": [{"type": "minecraft:constant", "value": -12012264}], 
    "minecraft:item/ocelot_spawn_egg": [{"type": "minecraft:constant", "value": -1057155}, {"type": "minecraft:constant", "value": -11123660}], 
    "minecraft:item/panda_spawn_egg": [{"type": "minecraft:constant", "value": -1579033}, {"type": "minecraft:constant", "value": -15000798}], 
    "minecraft:item/parrot_spawn_egg": [{"type": "minecraft:constant", "value": -15882485}, {"type": "minecraft:constant", "value": -65536}], 
    "minecraft:item/phantom_spawn_egg": [{"type": "minecraft:constant", "value": -12365430}, {"type": "minecraft:constant", "value": -7799040}], 
    "minecraft:item/piglin_brute_spawn_egg": [{"type": "minecraft:constant", "value": -10933744}, {"type": "minecraft:constant", "value": -396380}], 
    "minecraft:item/piglin_spawn_egg": [{"type": "minecraft:constant", "value": -6725824}, {"type": "minecraft:constant", "value": -396380}], 
    "minecraft:item/pig_spawn_egg": [{"type": "minecraft:constant", "value": -1006174}, {"type": "minecraft:constant", "value": -2399393}], 
    "minecraft:item/pillager_spawn_egg": [{"type": "minecraft:constant", "value": -11325642}, {"type": "minecraft:constant", "value": -6972517}], 
    "minecraft:item/polar_bear_spawn_egg": [{"type": "minecraft:constant", "value": -1118498}, {"type": "minecraft:constant", "value": -2763059}], 
    "minecraft:item/potion": [{"type": "minecraft:potion", "default": -13083194}], 
    "minecraft:item/pufferfish_spawn_egg": [{"type": "minecraft:constant", "value": -609791}, {"type": "minecraft:constant", "value": -13122574}], 
    "minecraft:item/rabbit_spawn_egg": [{"type": "minecraft:constant", "value": -6725824}, {"type": "minecraft:constant", "value": -9222095}], 
    "minecraft:item/ravager_spawn_egg": [{"type": "minecraft:constant", "value": -9079696}, {"type": "minecraft:constant", "value": -10792887}], 
    "minecraft:item/salmon_spawn_egg": [{"type": "minecraft:constant", "value": -6287600}, {"type": "minecraft:constant", "value": -15825804}], 
    "minecraft:item/sheep_spawn_egg": [{"type": "minecraft:constant", "value": -1579033}, {"type": "minecraft:constant", "value": -19019}], 
    "minecraft:item/short_grass": [{"type": "minecraft:grass", "downfall": 1.0, "temperature": 0.5}], 
    "minecraft:item/shulker_spawn_egg": [{"type": "minecraft:constant", "value": -7051372}, {"type": "minecraft:constant", "value": -11716526}], 
    "minecraft:item/silverfish_spawn_egg": [{"type": "minecraft:constant", "value": -9539986}, {"type": "minecraft:constant", "value": -13619152}], 
    "minecraft:item/skeleton_horse_spawn_egg": [{"type": "minecraft:constant", "value": -9934769}, {"type": "minecraft:constant", "value": -1710632}], 
    "minecraft:item/skeleton_spawn_egg": [{"type": "minecraft:constant", "value": -4079167}, {"type": "minecraft:constant", "value": -11974327}], 
    "minecraft:item/slime_spawn_egg": [{"type": "minecraft:constant", "value": -11427778}, {"type": "minecraft:constant", "value": -8470674}], 
    "minecraft:item/sniffer_spawn_egg": [{"type": "minecraft:constant", "value": -7922167}, {"type": "minecraft:constant", "value": -14308496}], 
    "minecraft:item/snow_golem_spawn_egg": [{"type": "minecraft:constant", "value": -2493710}, {"type": "minecraft:constant", "value": -8280924}], 
    "minecraft:item/spider_spawn_egg": [{"type": "minecraft:constant", "value": -13357785}, {"type": "minecraft:constant", "value": -5763570}], 
    "minecraft:item/splash_potion": [{"type": "minecraft:potion", "default": -13083194}], 
    "minecraft:item/spruce_leaves": [{"type": "minecraft:constant", "value": -10380959}], 
    "minecraft:item/squid_spawn_egg": [{"type": "minecraft:constant", "value": -14533811}, {"type": "minecraft:constant", "value": -9402215}], 
    "minecraft:item/stray_spawn_egg": [{"type": "minecraft:constant", "value": -10389897}, {"type": "minecraft:constant", "value": -2233622}], 
    "minecraft:item/strider_spawn_egg": [{"type": "minecraft:constant", "value": -6540234}, {"type": "minecraft:constant", "value": -11712179}], 
    "minecraft:item/tadpole_spawn_egg": [{"type": "minecraft:constant", "value": -9612483}, {"type": "minecraft:constant", "value": -15332864}], 
    "minecraft:item/tall_grass": [{"type": "minecraft:grass", "downfall": 1.0, "temperature": 0.5}], 
    "minecraft:item/tipped_arrow": [{"type": "minecraft:potion", "default": -13083194}], 
    "minecraft:item/trader_llama_spawn_egg": [{"type": "minecraft:constant", "value": -1399760}, {"type": "minecraft:constant", "value": -12229994}], 
    "minecraft:item/tropical_fish_spawn_egg": [{"type": "minecraft:constant", "value": -1087211}, {"type": "minecraft:constant", "value": -1553}], 
    "minecraft:item/turtle_spawn_egg": [{"type": "minecraft:constant", "value": -1579033}, {"type": "minecraft:constant", "value": -16732241}], 
    "minecraft:item/vex_spawn_egg": [{"type": "minecraft:constant", "value": -8744796}, {"type": "minecraft:constant", "value": -1511951}], 
    "minecraft:item/villager_spawn_egg": [{"type": "minecraft:constant", "value": -11125709}, {"type": "minecraft:constant", "value": -4355214}], 
    "minecraft:item/vindicator_spawn_egg": [{"type": "minecraft:constant", "value": -6972517}, {"type": "minecraft:constant", "value": -14197151}], 
    "minecraft:item/vine": [{"type": "minecraft:constant", "value": -12012264}], 
    "minecraft:item/wandering_trader_spawn_egg": [{"type": "minecraft:constant", "value": -12229994}, {"type": "minecraft:constant", "value": -1399760}], 
    "minecraft:item/warden_spawn_egg": [{"type": "minecraft:constant", "value": -15776183}, {"type": "minecraft:constant", "value": -12986656}], 
    "minecraft:item/witch_spawn_egg": [{"type": "minecraft:constant", "value": -13369344}, {"type": "minecraft:constant", "value": -11427778}], 
    "minecraft:item/wither_skeleton_spawn_egg": [{"type": "minecraft:constant", "value": -15461356}, {"type": "minecraft:constant", "value": -12104371}], 
    "minecraft:item/wither_spawn_egg": [{"type": "minecraft:constant", "value": -15461356}, {"type": "minecraft:constant", "value": -11701600}], 
    "minecraft:item/wolf_spawn_egg": [{"type": "minecraft:constant", "value": -2632749}, {"type": "minecraft:constant", "value": -3231850}], 
    "minecraft:item/zoglin_spawn_egg": [{"type": "minecraft:constant", "value": -3772843}, {"type": "minecraft:constant", "value": -1644826}], 
    "minecraft:item/zombie_horse_spawn_egg": [{"type": "minecraft:constant", "value": -13544908}, {"type": "minecraft:constant", "value": -6831484}], 
    "minecraft:item/zombie_spawn_egg": [{"type": "minecraft:constant", "value": -16732241}, {"type": "minecraft:constant", "value": -8807323}], 
    "minecraft:item/zombie_villager_spawn_egg": [{"type": "minecraft:constant", "value": -11125709}, {"type": "minecraft:constant", "value": -8807323}], 
    "minecraft:item/zombified_piglin_spawn_egg": [{"type": "minecraft:constant", "value": -1404013}, {"type": "minecraft:constant", "value": -11767511}]
}



BLOCK_MODEL_REPLACEMENTS: dict[str, str] = {
    "minecraft:item/acacia_fence_gate": "minecraft:block/acacia_fence_gate",
    "minecraft:item/acacia_leaves": "minecraft:block/acacia_leaves",
    "minecraft:item/acacia_log": "minecraft:block/acacia_log",
    "minecraft:item/acacia_planks": "minecraft:block/acacia_planks",
    "minecraft:item/acacia_pressure_plate": "minecraft:block/acacia_pressure_plate",
    "minecraft:item/acacia_slab": "minecraft:block/acacia_slab",
    "minecraft:item/acacia_stairs": "minecraft:block/acacia_stairs",
    "minecraft:item/acacia_wood": "minecraft:block/acacia_wood",
    "minecraft:item/amethyst_block": "minecraft:block/amethyst_block",
    "minecraft:item/ancient_debris": "minecraft:block/ancient_debris",
    "minecraft:item/andesite": "minecraft:block/andesite",
    "minecraft:item/andesite_slab": "minecraft:block/andesite_slab",
    "minecraft:item/andesite_stairs": "minecraft:block/andesite_stairs",
    "minecraft:item/anvil": "minecraft:block/anvil",
    "minecraft:item/azalea": "minecraft:block/azalea",
    "minecraft:item/azalea_leaves": "minecraft:block/azalea_leaves",
    "minecraft:item/bamboo_block": "minecraft:block/bamboo_block",
    "minecraft:item/bamboo_fence_gate": "minecraft:block/bamboo_fence_gate",
    "minecraft:item/bamboo_mosaic": "minecraft:block/bamboo_mosaic",
    "minecraft:item/bamboo_mosaic_slab": "minecraft:block/bamboo_mosaic_slab",
    "minecraft:item/bamboo_mosaic_stairs": "minecraft:block/bamboo_mosaic_stairs",
    "minecraft:item/bamboo_planks": "minecraft:block/bamboo_planks",
    "minecraft:item/bamboo_pressure_plate": "minecraft:block/bamboo_pressure_plate",
    "minecraft:item/bamboo_slab": "minecraft:block/bamboo_slab",
    "minecraft:item/bamboo_stairs": "minecraft:block/bamboo_stairs",
    "minecraft:item/barrel": "minecraft:block/barrel",
    "minecraft:item/basalt": "minecraft:block/basalt",
    "minecraft:item/beacon": "minecraft:block/beacon",
    "minecraft:item/bedrock": "minecraft:block/bedrock",
    "minecraft:item/big_dripleaf": "minecraft:block/big_dripleaf",
    "minecraft:item/birch_fence_gate": "minecraft:block/birch_fence_gate",
    "minecraft:item/birch_leaves": "minecraft:block/birch_leaves",
    "minecraft:item/birch_log": "minecraft:block/birch_log",
    "minecraft:item/birch_planks": "minecraft:block/birch_planks",
    "minecraft:item/birch_pressure_plate": "minecraft:block/birch_pressure_plate",
    "minecraft:item/birch_slab": "minecraft:block/birch_slab",
    "minecraft:item/birch_stairs": "minecraft:block/birch_stairs",
    "minecraft:item/birch_wood": "minecraft:block/birch_wood",
    "minecraft:item/blackstone": "minecraft:block/blackstone",
    "minecraft:item/blackstone_slab": "minecraft:block/blackstone_slab",
    "minecraft:item/blackstone_stairs": "minecraft:block/blackstone_stairs",
    "minecraft:item/black_carpet": "minecraft:block/black_carpet",
    "minecraft:item/black_concrete": "minecraft:block/black_concrete",
    "minecraft:item/black_concrete_powder": "minecraft:block/black_concrete_powder",
    "minecraft:item/black_glazed_terracotta": "minecraft:block/black_glazed_terracotta",
    "minecraft:item/black_stained_glass": "minecraft:block/black_stained_glass",
    "minecraft:item/black_terracotta": "minecraft:block/black_terracotta",
    "minecraft:item/black_wool": "minecraft:block/black_wool",
    "minecraft:item/blast_furnace": "minecraft:block/blast_furnace",
    "minecraft:item/blue_carpet": "minecraft:block/blue_carpet",
    "minecraft:item/blue_concrete": "minecraft:block/blue_concrete",
    "minecraft:item/blue_concrete_powder": "minecraft:block/blue_concrete_powder",
    "minecraft:item/blue_glazed_terracotta": "minecraft:block/blue_glazed_terracotta",
    "minecraft:item/blue_ice": "minecraft:block/blue_ice",
    "minecraft:item/blue_stained_glass": "minecraft:block/blue_stained_glass",
    "minecraft:item/blue_terracotta": "minecraft:block/blue_terracotta",
    "minecraft:item/blue_wool": "minecraft:block/blue_wool",
    "minecraft:item/bone_block": "minecraft:block/bone_block",
    "minecraft:item/bookshelf": "minecraft:block/bookshelf",
    "minecraft:item/brain_coral_block": "minecraft:block/brain_coral_block",
    "minecraft:item/bricks": "minecraft:block/bricks",
    "minecraft:item/brick_slab": "minecraft:block/brick_slab",
    "minecraft:item/brick_stairs": "minecraft:block/brick_stairs",
    "minecraft:item/brown_carpet": "minecraft:block/brown_carpet",
    "minecraft:item/brown_concrete": "minecraft:block/brown_concrete",
    "minecraft:item/brown_concrete_powder": "minecraft:block/brown_concrete_powder",
    "minecraft:item/brown_glazed_terracotta": "minecraft:block/brown_glazed_terracotta",
    "minecraft:item/brown_stained_glass": "minecraft:block/brown_stained_glass",
    "minecraft:item/brown_terracotta": "minecraft:block/brown_terracotta",
    "minecraft:item/brown_wool": "minecraft:block/brown_wool",
    "minecraft:item/bubble_coral_block": "minecraft:block/bubble_coral_block",
    "minecraft:item/budding_amethyst": "minecraft:block/budding_amethyst",
    "minecraft:item/cactus": "minecraft:block/cactus",
    "minecraft:item/calcite": "minecraft:block/calcite",
    "minecraft:item/cartography_table": "minecraft:block/cartography_table",
    "minecraft:item/carved_pumpkin": "minecraft:block/carved_pumpkin",
    "minecraft:item/chain_command_block": "minecraft:block/chain_command_block",
    "minecraft:item/cherry_fence_gate": "minecraft:block/cherry_fence_gate",
    "minecraft:item/cherry_leaves": "minecraft:block/cherry_leaves",
    "minecraft:item/cherry_log": "minecraft:block/cherry_log",
    "minecraft:item/cherry_planks": "minecraft:block/cherry_planks",
    "minecraft:item/cherry_pressure_plate": "minecraft:block/cherry_pressure_plate",
    "minecraft:item/cherry_slab": "minecraft:block/cherry_slab",
    "minecraft:item/cherry_stairs": "minecraft:block/cherry_stairs",
    "minecraft:item/cherry_wood": "minecraft:block/cherry_wood",
    "minecraft:item/chipped_anvil": "minecraft:block/chipped_anvil",
    "minecraft:item/chiseled_copper": "minecraft:block/chiseled_copper",
    "minecraft:item/chiseled_deepslate": "minecraft:block/chiseled_deepslate",
    "minecraft:item/chiseled_nether_bricks": "minecraft:block/chiseled_nether_bricks",
    "minecraft:item/chiseled_polished_blackstone": "minecraft:block/chiseled_polished_blackstone",
    "minecraft:item/chiseled_quartz_block": "minecraft:block/chiseled_quartz_block",
    "minecraft:item/chiseled_red_sandstone": "minecraft:block/chiseled_red_sandstone",
    "minecraft:item/chiseled_sandstone": "minecraft:block/chiseled_sandstone",
    "minecraft:item/chiseled_stone_bricks": "minecraft:block/chiseled_stone_bricks",
    "minecraft:item/chiseled_tuff": "minecraft:block/chiseled_tuff",
    "minecraft:item/chiseled_tuff_bricks": "minecraft:block/chiseled_tuff_bricks",
    "minecraft:item/chorus_flower": "minecraft:block/chorus_flower",
    "minecraft:item/chorus_plant": "minecraft:block/chorus_plant",
    "minecraft:item/clay": "minecraft:block/clay",
    "minecraft:item/coal_block": "minecraft:block/coal_block",
    "minecraft:item/coal_ore": "minecraft:block/coal_ore",
    "minecraft:item/coarse_dirt": "minecraft:block/coarse_dirt",
    "minecraft:item/cobbled_deepslate": "minecraft:block/cobbled_deepslate",
    "minecraft:item/cobbled_deepslate_slab": "minecraft:block/cobbled_deepslate_slab",
    "minecraft:item/cobbled_deepslate_stairs": "minecraft:block/cobbled_deepslate_stairs",
    "minecraft:item/cobblestone": "minecraft:block/cobblestone",
    "minecraft:item/cobblestone_slab": "minecraft:block/cobblestone_slab",
    "minecraft:item/cobblestone_stairs": "minecraft:block/cobblestone_stairs",
    "minecraft:item/command_block": "minecraft:block/command_block",
    "minecraft:item/composter": "minecraft:block/composter",
    "minecraft:item/copper_block": "minecraft:block/copper_block",
    "minecraft:item/copper_bulb": "minecraft:block/copper_bulb",
    "minecraft:item/copper_grate": "minecraft:block/copper_grate",
    "minecraft:item/copper_ore": "minecraft:block/copper_ore",
    "minecraft:item/cracked_deepslate_bricks": "minecraft:block/cracked_deepslate_bricks",
    "minecraft:item/cracked_deepslate_tiles": "minecraft:block/cracked_deepslate_tiles",
    "minecraft:item/cracked_nether_bricks": "minecraft:block/cracked_nether_bricks",
    "minecraft:item/cracked_polished_blackstone_bricks": "minecraft:block/cracked_polished_blackstone_bricks",
    "minecraft:item/cracked_stone_bricks": "minecraft:block/cracked_stone_bricks",
    "minecraft:item/crafter": "minecraft:block/crafter",
    "minecraft:item/crafting_table": "minecraft:block/crafting_table",
    "minecraft:item/creaking_heart": "minecraft:block/creaking_heart",
    "minecraft:item/crimson_fence_gate": "minecraft:block/crimson_fence_gate",
    "minecraft:item/crimson_hyphae": "minecraft:block/crimson_hyphae",
    "minecraft:item/crimson_nylium": "minecraft:block/crimson_nylium",
    "minecraft:item/crimson_planks": "minecraft:block/crimson_planks",
    "minecraft:item/crimson_pressure_plate": "minecraft:block/crimson_pressure_plate",
    "minecraft:item/crimson_slab": "minecraft:block/crimson_slab",
    "minecraft:item/crimson_stairs": "minecraft:block/crimson_stairs",
    "minecraft:item/crimson_stem": "minecraft:block/crimson_stem",
    "minecraft:item/crying_obsidian": "minecraft:block/crying_obsidian",
    "minecraft:item/cut_copper": "minecraft:block/cut_copper",
    "minecraft:item/cut_copper_slab": "minecraft:block/cut_copper_slab",
    "minecraft:item/cut_copper_stairs": "minecraft:block/cut_copper_stairs",
    "minecraft:item/cut_red_sandstone": "minecraft:block/cut_red_sandstone",
    "minecraft:item/cut_red_sandstone_slab": "minecraft:block/cut_red_sandstone_slab",
    "minecraft:item/cut_sandstone": "minecraft:block/cut_sandstone",
    "minecraft:item/cut_sandstone_slab": "minecraft:block/cut_sandstone_slab",
    "minecraft:item/cyan_carpet": "minecraft:block/cyan_carpet",
    "minecraft:item/cyan_concrete": "minecraft:block/cyan_concrete",
    "minecraft:item/cyan_concrete_powder": "minecraft:block/cyan_concrete_powder",
    "minecraft:item/cyan_glazed_terracotta": "minecraft:block/cyan_glazed_terracotta",
    "minecraft:item/cyan_stained_glass": "minecraft:block/cyan_stained_glass",
    "minecraft:item/cyan_terracotta": "minecraft:block/cyan_terracotta",
    "minecraft:item/cyan_wool": "minecraft:block/cyan_wool",
    "minecraft:item/damaged_anvil": "minecraft:block/damaged_anvil",
    "minecraft:item/dark_oak_fence_gate": "minecraft:block/dark_oak_fence_gate",
    "minecraft:item/dark_oak_leaves": "minecraft:block/dark_oak_leaves",
    "minecraft:item/dark_oak_log": "minecraft:block/dark_oak_log",
    "minecraft:item/dark_oak_planks": "minecraft:block/dark_oak_planks",
    "minecraft:item/dark_oak_pressure_plate": "minecraft:block/dark_oak_pressure_plate",
    "minecraft:item/dark_oak_slab": "minecraft:block/dark_oak_slab",
    "minecraft:item/dark_oak_stairs": "minecraft:block/dark_oak_stairs",
    "minecraft:item/dark_oak_wood": "minecraft:block/dark_oak_wood",
    "minecraft:item/dark_prismarine": "minecraft:block/dark_prismarine",
    "minecraft:item/dark_prismarine_slab": "minecraft:block/dark_prismarine_slab",
    "minecraft:item/dark_prismarine_stairs": "minecraft:block/dark_prismarine_stairs",
    "minecraft:item/daylight_detector": "minecraft:block/daylight_detector",
    "minecraft:item/dead_brain_coral_block": "minecraft:block/dead_brain_coral_block",
    "minecraft:item/dead_bubble_coral_block": "minecraft:block/dead_bubble_coral_block",
    "minecraft:item/dead_fire_coral_block": "minecraft:block/dead_fire_coral_block",
    "minecraft:item/dead_horn_coral_block": "minecraft:block/dead_horn_coral_block",
    "minecraft:item/dead_tube_coral_block": "minecraft:block/dead_tube_coral_block",
    "minecraft:item/deepslate": "minecraft:block/deepslate",
    "minecraft:item/deepslate_bricks": "minecraft:block/deepslate_bricks",
    "minecraft:item/deepslate_brick_slab": "minecraft:block/deepslate_brick_slab",
    "minecraft:item/deepslate_brick_stairs": "minecraft:block/deepslate_brick_stairs",
    "minecraft:item/deepslate_coal_ore": "minecraft:block/deepslate_coal_ore",
    "minecraft:item/deepslate_copper_ore": "minecraft:block/deepslate_copper_ore",
    "minecraft:item/deepslate_diamond_ore": "minecraft:block/deepslate_diamond_ore",
    "minecraft:item/deepslate_emerald_ore": "minecraft:block/deepslate_emerald_ore",
    "minecraft:item/deepslate_gold_ore": "minecraft:block/deepslate_gold_ore",
    "minecraft:item/deepslate_iron_ore": "minecraft:block/deepslate_iron_ore",
    "minecraft:item/deepslate_lapis_ore": "minecraft:block/deepslate_lapis_ore",
    "minecraft:item/deepslate_redstone_ore": "minecraft:block/deepslate_redstone_ore",
    "minecraft:item/deepslate_tiles": "minecraft:block/deepslate_tiles",
    "minecraft:item/deepslate_tile_slab": "minecraft:block/deepslate_tile_slab",
    "minecraft:item/deepslate_tile_stairs": "minecraft:block/deepslate_tile_stairs",
    "minecraft:item/diamond_block": "minecraft:block/diamond_block",
    "minecraft:item/diamond_ore": "minecraft:block/diamond_ore",
    "minecraft:item/diorite": "minecraft:block/diorite",
    "minecraft:item/diorite_slab": "minecraft:block/diorite_slab",
    "minecraft:item/diorite_stairs": "minecraft:block/diorite_stairs",
    "minecraft:item/dirt": "minecraft:block/dirt",
    "minecraft:item/dirt_path": "minecraft:block/dirt_path",
    "minecraft:item/dispenser": "minecraft:block/dispenser",
    "minecraft:item/dragon_egg": "minecraft:block/dragon_egg",
    "minecraft:item/dried_kelp_block": "minecraft:block/dried_kelp_block",
    "minecraft:item/dripstone_block": "minecraft:block/dripstone_block",
    "minecraft:item/dropper": "minecraft:block/dropper",
    "minecraft:item/emerald_block": "minecraft:block/emerald_block",
    "minecraft:item/emerald_ore": "minecraft:block/emerald_ore",
    "minecraft:item/enchanting_table": "minecraft:block/enchanting_table",
    "minecraft:item/end_portal_frame": "minecraft:block/end_portal_frame",
    "minecraft:item/end_rod": "minecraft:block/end_rod",
    "minecraft:item/end_stone": "minecraft:block/end_stone",
    "minecraft:item/end_stone_bricks": "minecraft:block/end_stone_bricks",
    "minecraft:item/end_stone_brick_slab": "minecraft:block/end_stone_brick_slab",
    "minecraft:item/end_stone_brick_stairs": "minecraft:block/end_stone_brick_stairs",
    "minecraft:item/exposed_chiseled_copper": "minecraft:block/exposed_chiseled_copper",
    "minecraft:item/exposed_copper": "minecraft:block/exposed_copper",
    "minecraft:item/exposed_copper_bulb": "minecraft:block/exposed_copper_bulb",
    "minecraft:item/exposed_copper_grate": "minecraft:block/exposed_copper_grate",
    "minecraft:item/exposed_cut_copper": "minecraft:block/exposed_cut_copper",
    "minecraft:item/exposed_cut_copper_slab": "minecraft:block/exposed_cut_copper_slab",
    "minecraft:item/exposed_cut_copper_stairs": "minecraft:block/exposed_cut_copper_stairs",
    "minecraft:item/farmland": "minecraft:block/farmland",
    "minecraft:item/fire_coral_block": "minecraft:block/fire_coral_block",
    "minecraft:item/fletching_table": "minecraft:block/fletching_table",
    "minecraft:item/flowering_azalea": "minecraft:block/flowering_azalea",
    "minecraft:item/flowering_azalea_leaves": "minecraft:block/flowering_azalea_leaves",
    "minecraft:item/furnace": "minecraft:block/furnace",
    "minecraft:item/gilded_blackstone": "minecraft:block/gilded_blackstone",
    "minecraft:item/glass": "minecraft:block/glass",
    "minecraft:item/glowstone": "minecraft:block/glowstone",
    "minecraft:item/gold_block": "minecraft:block/gold_block",
    "minecraft:item/gold_ore": "minecraft:block/gold_ore",
    "minecraft:item/granite": "minecraft:block/granite",
    "minecraft:item/granite_slab": "minecraft:block/granite_slab",
    "minecraft:item/granite_stairs": "minecraft:block/granite_stairs",
    "minecraft:item/grass_block": "minecraft:block/grass_block",
    "minecraft:item/gravel": "minecraft:block/gravel",
    "minecraft:item/gray_carpet": "minecraft:block/gray_carpet",
    "minecraft:item/gray_concrete": "minecraft:block/gray_concrete",
    "minecraft:item/gray_concrete_powder": "minecraft:block/gray_concrete_powder",
    "minecraft:item/gray_glazed_terracotta": "minecraft:block/gray_glazed_terracotta",
    "minecraft:item/gray_stained_glass": "minecraft:block/gray_stained_glass",
    "minecraft:item/gray_terracotta": "minecraft:block/gray_terracotta",
    "minecraft:item/gray_wool": "minecraft:block/gray_wool",
    "minecraft:item/green_carpet": "minecraft:block/green_carpet",
    "minecraft:item/green_concrete": "minecraft:block/green_concrete",
    "minecraft:item/green_concrete_powder": "minecraft:block/green_concrete_powder",
    "minecraft:item/green_glazed_terracotta": "minecraft:block/green_glazed_terracotta",
    "minecraft:item/green_stained_glass": "minecraft:block/green_stained_glass",
    "minecraft:item/green_terracotta": "minecraft:block/green_terracotta",
    "minecraft:item/green_wool": "minecraft:block/green_wool",
    "minecraft:item/grindstone": "minecraft:block/grindstone",
    "minecraft:item/hay_block": "minecraft:block/hay_block",
    "minecraft:item/heavy_core": "minecraft:block/heavy_core",
    "minecraft:item/heavy_weighted_pressure_plate": "minecraft:block/heavy_weighted_pressure_plate",
    "minecraft:item/honeycomb_block": "minecraft:block/honeycomb_block",
    "minecraft:item/honey_block": "minecraft:block/honey_block",
    "minecraft:item/horn_coral_block": "minecraft:block/horn_coral_block",
    "minecraft:item/ice": "minecraft:block/ice",
    "minecraft:item/iron_block": "minecraft:block/iron_block",
    "minecraft:item/iron_ore": "minecraft:block/iron_ore",
    "minecraft:item/jack_o_lantern": "minecraft:block/jack_o_lantern",
    "minecraft:item/jigsaw": "minecraft:block/jigsaw",
    "minecraft:item/jukebox": "minecraft:block/jukebox",
    "minecraft:item/jungle_fence_gate": "minecraft:block/jungle_fence_gate",
    "minecraft:item/jungle_leaves": "minecraft:block/jungle_leaves",
    "minecraft:item/jungle_log": "minecraft:block/jungle_log",
    "minecraft:item/jungle_planks": "minecraft:block/jungle_planks",
    "minecraft:item/jungle_pressure_plate": "minecraft:block/jungle_pressure_plate",
    "minecraft:item/jungle_slab": "minecraft:block/jungle_slab",
    "minecraft:item/jungle_stairs": "minecraft:block/jungle_stairs",
    "minecraft:item/jungle_wood": "minecraft:block/jungle_wood",
    "minecraft:item/lapis_block": "minecraft:block/lapis_block",
    "minecraft:item/lapis_ore": "minecraft:block/lapis_ore",
    "minecraft:item/lectern": "minecraft:block/lectern",
    "minecraft:item/lightning_rod": "minecraft:block/lightning_rod",
    "minecraft:item/light_blue_carpet": "minecraft:block/light_blue_carpet",
    "minecraft:item/light_blue_concrete": "minecraft:block/light_blue_concrete",
    "minecraft:item/light_blue_concrete_powder": "minecraft:block/light_blue_concrete_powder",
    "minecraft:item/light_blue_glazed_terracotta": "minecraft:block/light_blue_glazed_terracotta",
    "minecraft:item/light_blue_stained_glass": "minecraft:block/light_blue_stained_glass",
    "minecraft:item/light_blue_terracotta": "minecraft:block/light_blue_terracotta",
    "minecraft:item/light_blue_wool": "minecraft:block/light_blue_wool",
    "minecraft:item/light_gray_carpet": "minecraft:block/light_gray_carpet",
    "minecraft:item/light_gray_concrete": "minecraft:block/light_gray_concrete",
    "minecraft:item/light_gray_concrete_powder": "minecraft:block/light_gray_concrete_powder",
    "minecraft:item/light_gray_glazed_terracotta": "minecraft:block/light_gray_glazed_terracotta",
    "minecraft:item/light_gray_stained_glass": "minecraft:block/light_gray_stained_glass",
    "minecraft:item/light_gray_terracotta": "minecraft:block/light_gray_terracotta",
    "minecraft:item/light_gray_wool": "minecraft:block/light_gray_wool",
    "minecraft:item/light_weighted_pressure_plate": "minecraft:block/light_weighted_pressure_plate",
    "minecraft:item/lime_carpet": "minecraft:block/lime_carpet",
    "minecraft:item/lime_concrete": "minecraft:block/lime_concrete",
    "minecraft:item/lime_concrete_powder": "minecraft:block/lime_concrete_powder",
    "minecraft:item/lime_glazed_terracotta": "minecraft:block/lime_glazed_terracotta",
    "minecraft:item/lime_stained_glass": "minecraft:block/lime_stained_glass",
    "minecraft:item/lime_terracotta": "minecraft:block/lime_terracotta",
    "minecraft:item/lime_wool": "minecraft:block/lime_wool",
    "minecraft:item/lodestone": "minecraft:block/lodestone",
    "minecraft:item/loom": "minecraft:block/loom",
    "minecraft:item/magenta_carpet": "minecraft:block/magenta_carpet",
    "minecraft:item/magenta_concrete": "minecraft:block/magenta_concrete",
    "minecraft:item/magenta_concrete_powder": "minecraft:block/magenta_concrete_powder",
    "minecraft:item/magenta_glazed_terracotta": "minecraft:block/magenta_glazed_terracotta",
    "minecraft:item/magenta_stained_glass": "minecraft:block/magenta_stained_glass",
    "minecraft:item/magenta_terracotta": "minecraft:block/magenta_terracotta",
    "minecraft:item/magenta_wool": "minecraft:block/magenta_wool",
    "minecraft:item/magma_block": "minecraft:block/magma_block",
    "minecraft:item/mangrove_fence_gate": "minecraft:block/mangrove_fence_gate",
    "minecraft:item/mangrove_leaves": "minecraft:block/mangrove_leaves",
    "minecraft:item/mangrove_log": "minecraft:block/mangrove_log",
    "minecraft:item/mangrove_planks": "minecraft:block/mangrove_planks",
    "minecraft:item/mangrove_pressure_plate": "minecraft:block/mangrove_pressure_plate",
    "minecraft:item/mangrove_roots": "minecraft:block/mangrove_roots",
    "minecraft:item/mangrove_slab": "minecraft:block/mangrove_slab",
    "minecraft:item/mangrove_stairs": "minecraft:block/mangrove_stairs",
    "minecraft:item/mangrove_wood": "minecraft:block/mangrove_wood",
    "minecraft:item/melon": "minecraft:block/melon",
    "minecraft:item/mossy_cobblestone": "minecraft:block/mossy_cobblestone",
    "minecraft:item/mossy_cobblestone_slab": "minecraft:block/mossy_cobblestone_slab",
    "minecraft:item/mossy_cobblestone_stairs": "minecraft:block/mossy_cobblestone_stairs",
    "minecraft:item/mossy_stone_bricks": "minecraft:block/mossy_stone_bricks",
    "minecraft:item/mossy_stone_brick_slab": "minecraft:block/mossy_stone_brick_slab",
    "minecraft:item/mossy_stone_brick_stairs": "minecraft:block/mossy_stone_brick_stairs",
    "minecraft:item/moss_block": "minecraft:block/moss_block",
    "minecraft:item/moss_carpet": "minecraft:block/moss_carpet",
    "minecraft:item/mud": "minecraft:block/mud",
    "minecraft:item/muddy_mangrove_roots": "minecraft:block/muddy_mangrove_roots",
    "minecraft:item/mud_bricks": "minecraft:block/mud_bricks",
    "minecraft:item/mud_brick_slab": "minecraft:block/mud_brick_slab",
    "minecraft:item/mud_brick_stairs": "minecraft:block/mud_brick_stairs",
    "minecraft:item/mycelium": "minecraft:block/mycelium",
    "minecraft:item/netherite_block": "minecraft:block/netherite_block",
    "minecraft:item/netherrack": "minecraft:block/netherrack",
    "minecraft:item/nether_bricks": "minecraft:block/nether_bricks",
    "minecraft:item/nether_brick_slab": "minecraft:block/nether_brick_slab",
    "minecraft:item/nether_brick_stairs": "minecraft:block/nether_brick_stairs",
    "minecraft:item/nether_gold_ore": "minecraft:block/nether_gold_ore",
    "minecraft:item/nether_quartz_ore": "minecraft:block/nether_quartz_ore",
    "minecraft:item/nether_wart_block": "minecraft:block/nether_wart_block",
    "minecraft:item/note_block": "minecraft:block/note_block",
    "minecraft:item/oak_fence_gate": "minecraft:block/oak_fence_gate",
    "minecraft:item/oak_leaves": "minecraft:block/oak_leaves",
    "minecraft:item/oak_log": "minecraft:block/oak_log",
    "minecraft:item/oak_planks": "minecraft:block/oak_planks",
    "minecraft:item/oak_pressure_plate": "minecraft:block/oak_pressure_plate",
    "minecraft:item/oak_slab": "minecraft:block/oak_slab",
    "minecraft:item/oak_stairs": "minecraft:block/oak_stairs",
    "minecraft:item/oak_wood": "minecraft:block/oak_wood",
    "minecraft:item/observer": "minecraft:block/observer",
    "minecraft:item/obsidian": "minecraft:block/obsidian",
    "minecraft:item/ochre_froglight": "minecraft:block/ochre_froglight",
    "minecraft:item/orange_carpet": "minecraft:block/orange_carpet",
    "minecraft:item/orange_concrete": "minecraft:block/orange_concrete",
    "minecraft:item/orange_concrete_powder": "minecraft:block/orange_concrete_powder",
    "minecraft:item/orange_glazed_terracotta": "minecraft:block/orange_glazed_terracotta",
    "minecraft:item/orange_stained_glass": "minecraft:block/orange_stained_glass",
    "minecraft:item/orange_terracotta": "minecraft:block/orange_terracotta",
    "minecraft:item/orange_wool": "minecraft:block/orange_wool",
    "minecraft:item/oxidized_chiseled_copper": "minecraft:block/oxidized_chiseled_copper",
    "minecraft:item/oxidized_copper": "minecraft:block/oxidized_copper",
    "minecraft:item/oxidized_copper_bulb": "minecraft:block/oxidized_copper_bulb",
    "minecraft:item/oxidized_copper_grate": "minecraft:block/oxidized_copper_grate",
    "minecraft:item/oxidized_cut_copper": "minecraft:block/oxidized_cut_copper",
    "minecraft:item/oxidized_cut_copper_slab": "minecraft:block/oxidized_cut_copper_slab",
    "minecraft:item/oxidized_cut_copper_stairs": "minecraft:block/oxidized_cut_copper_stairs",
    "minecraft:item/packed_ice": "minecraft:block/packed_ice",
    "minecraft:item/packed_mud": "minecraft:block/packed_mud",
    "minecraft:item/pale_moss_block": "minecraft:block/pale_moss_block",
    "minecraft:item/pale_moss_carpet": "minecraft:block/pale_moss_carpet",
    "minecraft:item/pale_oak_fence_gate": "minecraft:block/pale_oak_fence_gate",
    "minecraft:item/pale_oak_leaves": "minecraft:block/pale_oak_leaves",
    "minecraft:item/pale_oak_log": "minecraft:block/pale_oak_log",
    "minecraft:item/pale_oak_planks": "minecraft:block/pale_oak_planks",
    "minecraft:item/pale_oak_pressure_plate": "minecraft:block/pale_oak_pressure_plate",
    "minecraft:item/pale_oak_slab": "minecraft:block/pale_oak_slab",
    "minecraft:item/pale_oak_stairs": "minecraft:block/pale_oak_stairs",
    "minecraft:item/pale_oak_wood": "minecraft:block/pale_oak_wood",
    "minecraft:item/pearlescent_froglight": "minecraft:block/pearlescent_froglight",
    "minecraft:item/petrified_oak_slab": "minecraft:block/petrified_oak_slab",
    "minecraft:item/pink_carpet": "minecraft:block/pink_carpet",
    "minecraft:item/pink_concrete": "minecraft:block/pink_concrete",
    "minecraft:item/pink_concrete_powder": "minecraft:block/pink_concrete_powder",
    "minecraft:item/pink_glazed_terracotta": "minecraft:block/pink_glazed_terracotta",
    "minecraft:item/pink_stained_glass": "minecraft:block/pink_stained_glass",
    "minecraft:item/pink_terracotta": "minecraft:block/pink_terracotta",
    "minecraft:item/pink_wool": "minecraft:block/pink_wool",
    "minecraft:item/podzol": "minecraft:block/podzol",
    "minecraft:item/polished_andesite": "minecraft:block/polished_andesite",
    "minecraft:item/polished_andesite_slab": "minecraft:block/polished_andesite_slab",
    "minecraft:item/polished_andesite_stairs": "minecraft:block/polished_andesite_stairs",
    "minecraft:item/polished_basalt": "minecraft:block/polished_basalt",
    "minecraft:item/polished_blackstone": "minecraft:block/polished_blackstone",
    "minecraft:item/polished_blackstone_bricks": "minecraft:block/polished_blackstone_bricks",
    "minecraft:item/polished_blackstone_brick_slab": "minecraft:block/polished_blackstone_brick_slab",
    "minecraft:item/polished_blackstone_brick_stairs": "minecraft:block/polished_blackstone_brick_stairs",
    "minecraft:item/polished_blackstone_pressure_plate": "minecraft:block/polished_blackstone_pressure_plate",
    "minecraft:item/polished_blackstone_slab": "minecraft:block/polished_blackstone_slab",
    "minecraft:item/polished_blackstone_stairs": "minecraft:block/polished_blackstone_stairs",
    "minecraft:item/polished_deepslate": "minecraft:block/polished_deepslate",
    "minecraft:item/polished_deepslate_slab": "minecraft:block/polished_deepslate_slab",
    "minecraft:item/polished_deepslate_stairs": "minecraft:block/polished_deepslate_stairs",
    "minecraft:item/polished_diorite": "minecraft:block/polished_diorite",
    "minecraft:item/polished_diorite_slab": "minecraft:block/polished_diorite_slab",
    "minecraft:item/polished_diorite_stairs": "minecraft:block/polished_diorite_stairs",
    "minecraft:item/polished_granite": "minecraft:block/polished_granite",
    "minecraft:item/polished_granite_slab": "minecraft:block/polished_granite_slab",
    "minecraft:item/polished_granite_stairs": "minecraft:block/polished_granite_stairs",
    "minecraft:item/polished_tuff": "minecraft:block/polished_tuff",
    "minecraft:item/polished_tuff_slab": "minecraft:block/polished_tuff_slab",
    "minecraft:item/polished_tuff_stairs": "minecraft:block/polished_tuff_stairs",
    "minecraft:item/prismarine": "minecraft:block/prismarine",
    "minecraft:item/prismarine_bricks": "minecraft:block/prismarine_bricks",
    "minecraft:item/prismarine_brick_slab": "minecraft:block/prismarine_brick_slab",
    "minecraft:item/prismarine_brick_stairs": "minecraft:block/prismarine_brick_stairs",
    "minecraft:item/prismarine_slab": "minecraft:block/prismarine_slab",
    "minecraft:item/prismarine_stairs": "minecraft:block/prismarine_stairs",
    "minecraft:item/pumpkin": "minecraft:block/pumpkin",
    "minecraft:item/purple_carpet": "minecraft:block/purple_carpet",
    "minecraft:item/purple_concrete": "minecraft:block/purple_concrete",
    "minecraft:item/purple_concrete_powder": "minecraft:block/purple_concrete_powder",
    "minecraft:item/purple_glazed_terracotta": "minecraft:block/purple_glazed_terracotta",
    "minecraft:item/purple_stained_glass": "minecraft:block/purple_stained_glass",
    "minecraft:item/purple_terracotta": "minecraft:block/purple_terracotta",
    "minecraft:item/purple_wool": "minecraft:block/purple_wool",
    "minecraft:item/purpur_block": "minecraft:block/purpur_block",
    "minecraft:item/purpur_pillar": "minecraft:block/purpur_pillar",
    "minecraft:item/purpur_slab": "minecraft:block/purpur_slab",
    "minecraft:item/purpur_stairs": "minecraft:block/purpur_stairs",
    "minecraft:item/quartz_block": "minecraft:block/quartz_block",
    "minecraft:item/quartz_bricks": "minecraft:block/quartz_bricks",
    "minecraft:item/quartz_pillar": "minecraft:block/quartz_pillar",
    "minecraft:item/quartz_slab": "minecraft:block/quartz_slab",
    "minecraft:item/quartz_stairs": "minecraft:block/quartz_stairs",
    "minecraft:item/raw_copper_block": "minecraft:block/raw_copper_block",
    "minecraft:item/raw_gold_block": "minecraft:block/raw_gold_block",
    "minecraft:item/raw_iron_block": "minecraft:block/raw_iron_block",
    "minecraft:item/redstone_block": "minecraft:block/redstone_block",
    "minecraft:item/redstone_lamp": "minecraft:block/redstone_lamp",
    "minecraft:item/redstone_ore": "minecraft:block/redstone_ore",
    "minecraft:item/red_carpet": "minecraft:block/red_carpet",
    "minecraft:item/red_concrete": "minecraft:block/red_concrete",
    "minecraft:item/red_concrete_powder": "minecraft:block/red_concrete_powder",
    "minecraft:item/red_glazed_terracotta": "minecraft:block/red_glazed_terracotta",
    "minecraft:item/red_nether_bricks": "minecraft:block/red_nether_bricks",
    "minecraft:item/red_nether_brick_slab": "minecraft:block/red_nether_brick_slab",
    "minecraft:item/red_nether_brick_stairs": "minecraft:block/red_nether_brick_stairs",
    "minecraft:item/red_sand": "minecraft:block/red_sand",
    "minecraft:item/red_sandstone": "minecraft:block/red_sandstone",
    "minecraft:item/red_sandstone_slab": "minecraft:block/red_sandstone_slab",
    "minecraft:item/red_sandstone_stairs": "minecraft:block/red_sandstone_stairs",
    "minecraft:item/red_stained_glass": "minecraft:block/red_stained_glass",
    "minecraft:item/red_terracotta": "minecraft:block/red_terracotta",
    "minecraft:item/red_wool": "minecraft:block/red_wool",
    "minecraft:item/reinforced_deepslate": "minecraft:block/reinforced_deepslate",
    "minecraft:item/repeating_command_block": "minecraft:block/repeating_command_block",
    "minecraft:item/rooted_dirt": "minecraft:block/rooted_dirt",
    "minecraft:item/sand": "minecraft:block/sand",
    "minecraft:item/sandstone": "minecraft:block/sandstone",
    "minecraft:item/sandstone_slab": "minecraft:block/sandstone_slab",
    "minecraft:item/sandstone_stairs": "minecraft:block/sandstone_stairs",
    "minecraft:item/sculk": "minecraft:block/sculk",
    "minecraft:item/sculk_catalyst": "minecraft:block/sculk_catalyst",
    "minecraft:item/sculk_shrieker": "minecraft:block/sculk_shrieker",
    "minecraft:item/sea_lantern": "minecraft:block/sea_lantern",
    "minecraft:item/shroomlight": "minecraft:block/shroomlight",
    "minecraft:item/slime_block": "minecraft:block/slime_block",
    "minecraft:item/smithing_table": "minecraft:block/smithing_table",
    "minecraft:item/smoker": "minecraft:block/smoker",
    "minecraft:item/smooth_basalt": "minecraft:block/smooth_basalt",
    "minecraft:item/smooth_quartz": "minecraft:block/smooth_quartz",
    "minecraft:item/smooth_quartz_slab": "minecraft:block/smooth_quartz_slab",
    "minecraft:item/smooth_quartz_stairs": "minecraft:block/smooth_quartz_stairs",
    "minecraft:item/smooth_red_sandstone": "minecraft:block/smooth_red_sandstone",
    "minecraft:item/smooth_red_sandstone_slab": "minecraft:block/smooth_red_sandstone_slab",
    "minecraft:item/smooth_red_sandstone_stairs": "minecraft:block/smooth_red_sandstone_stairs",
    "minecraft:item/smooth_sandstone": "minecraft:block/smooth_sandstone",
    "minecraft:item/smooth_sandstone_slab": "minecraft:block/smooth_sandstone_slab",
    "minecraft:item/smooth_sandstone_stairs": "minecraft:block/smooth_sandstone_stairs",
    "minecraft:item/smooth_stone": "minecraft:block/smooth_stone",
    "minecraft:item/smooth_stone_slab": "minecraft:block/smooth_stone_slab",
    "minecraft:item/snow_block": "minecraft:block/snow_block",
    "minecraft:item/soul_sand": "minecraft:block/soul_sand",
    "minecraft:item/soul_soil": "minecraft:block/soul_soil",
    "minecraft:item/spawner": "minecraft:block/spawner",
    "minecraft:item/sponge": "minecraft:block/sponge",
    "minecraft:item/spore_blossom": "minecraft:block/spore_blossom",
    "minecraft:item/spruce_fence_gate": "minecraft:block/spruce_fence_gate",
    "minecraft:item/spruce_leaves": "minecraft:block/spruce_leaves",
    "minecraft:item/spruce_log": "minecraft:block/spruce_log",
    "minecraft:item/spruce_planks": "minecraft:block/spruce_planks",
    "minecraft:item/spruce_pressure_plate": "minecraft:block/spruce_pressure_plate",
    "minecraft:item/spruce_slab": "minecraft:block/spruce_slab",
    "minecraft:item/spruce_stairs": "minecraft:block/spruce_stairs",
    "minecraft:item/spruce_wood": "minecraft:block/spruce_wood",
    "minecraft:item/stone": "minecraft:block/stone",
    "minecraft:item/stonecutter": "minecraft:block/stonecutter",
    "minecraft:item/stone_bricks": "minecraft:block/stone_bricks",
    "minecraft:item/stone_brick_slab": "minecraft:block/stone_brick_slab",
    "minecraft:item/stone_brick_stairs": "minecraft:block/stone_brick_stairs",
    "minecraft:item/stone_pressure_plate": "minecraft:block/stone_pressure_plate",
    "minecraft:item/stone_slab": "minecraft:block/stone_slab",
    "minecraft:item/stone_stairs": "minecraft:block/stone_stairs",
    "minecraft:item/stripped_acacia_log": "minecraft:block/stripped_acacia_log",
    "minecraft:item/stripped_acacia_wood": "minecraft:block/stripped_acacia_wood",
    "minecraft:item/stripped_bamboo_block": "minecraft:block/stripped_bamboo_block",
    "minecraft:item/stripped_birch_log": "minecraft:block/stripped_birch_log",
    "minecraft:item/stripped_birch_wood": "minecraft:block/stripped_birch_wood",
    "minecraft:item/stripped_cherry_log": "minecraft:block/stripped_cherry_log",
    "minecraft:item/stripped_cherry_wood": "minecraft:block/stripped_cherry_wood",
    "minecraft:item/stripped_crimson_hyphae": "minecraft:block/stripped_crimson_hyphae",
    "minecraft:item/stripped_crimson_stem": "minecraft:block/stripped_crimson_stem",
    "minecraft:item/stripped_dark_oak_log": "minecraft:block/stripped_dark_oak_log",
    "minecraft:item/stripped_dark_oak_wood": "minecraft:block/stripped_dark_oak_wood",
    "minecraft:item/stripped_jungle_log": "minecraft:block/stripped_jungle_log",
    "minecraft:item/stripped_jungle_wood": "minecraft:block/stripped_jungle_wood",
    "minecraft:item/stripped_mangrove_log": "minecraft:block/stripped_mangrove_log",
    "minecraft:item/stripped_mangrove_wood": "minecraft:block/stripped_mangrove_wood",
    "minecraft:item/stripped_oak_log": "minecraft:block/stripped_oak_log",
    "minecraft:item/stripped_oak_wood": "minecraft:block/stripped_oak_wood",
    "minecraft:item/stripped_pale_oak_log": "minecraft:block/stripped_pale_oak_log",
    "minecraft:item/stripped_pale_oak_wood": "minecraft:block/stripped_pale_oak_wood",
    "minecraft:item/stripped_spruce_log": "minecraft:block/stripped_spruce_log",
    "minecraft:item/stripped_spruce_wood": "minecraft:block/stripped_spruce_wood",
    "minecraft:item/stripped_warped_hyphae": "minecraft:block/stripped_warped_hyphae",
    "minecraft:item/stripped_warped_stem": "minecraft:block/stripped_warped_stem",
    "minecraft:item/structure_block": "minecraft:block/structure_block",
    "minecraft:item/target": "minecraft:block/target",
    "minecraft:item/terracotta": "minecraft:block/terracotta",
    "minecraft:item/tinted_glass": "minecraft:block/tinted_glass",
    "minecraft:item/tnt": "minecraft:block/tnt",
    "minecraft:item/trial_spawner": "minecraft:block/trial_spawner",
    "minecraft:item/tube_coral_block": "minecraft:block/tube_coral_block",
    "minecraft:item/tuff": "minecraft:block/tuff",
    "minecraft:item/tuff_bricks": "minecraft:block/tuff_bricks",
    "minecraft:item/tuff_brick_slab": "minecraft:block/tuff_brick_slab",
    "minecraft:item/tuff_brick_stairs": "minecraft:block/tuff_brick_stairs",
    "minecraft:item/tuff_slab": "minecraft:block/tuff_slab",
    "minecraft:item/tuff_stairs": "minecraft:block/tuff_stairs",
    "minecraft:item/vault": "minecraft:block/vault",
    "minecraft:item/verdant_froglight": "minecraft:block/verdant_froglight",
    "minecraft:item/warped_fence_gate": "minecraft:block/warped_fence_gate",
    "minecraft:item/warped_hyphae": "minecraft:block/warped_hyphae",
    "minecraft:item/warped_nylium": "minecraft:block/warped_nylium",
    "minecraft:item/warped_planks": "minecraft:block/warped_planks",
    "minecraft:item/warped_pressure_plate": "minecraft:block/warped_pressure_plate",
    "minecraft:item/warped_slab": "minecraft:block/warped_slab",
    "minecraft:item/warped_stairs": "minecraft:block/warped_stairs",
    "minecraft:item/warped_stem": "minecraft:block/warped_stem",
    "minecraft:item/warped_wart_block": "minecraft:block/warped_wart_block",
    "minecraft:item/weathered_chiseled_copper": "minecraft:block/weathered_chiseled_copper",
    "minecraft:item/weathered_copper": "minecraft:block/weathered_copper",
    "minecraft:item/weathered_copper_bulb": "minecraft:block/weathered_copper_bulb",
    "minecraft:item/weathered_copper_grate": "minecraft:block/weathered_copper_grate",
    "minecraft:item/weathered_cut_copper": "minecraft:block/weathered_cut_copper",
    "minecraft:item/weathered_cut_copper_slab": "minecraft:block/weathered_cut_copper_slab",
    "minecraft:item/weathered_cut_copper_stairs": "minecraft:block/weathered_cut_copper_stairs",
    "minecraft:item/wet_sponge": "minecraft:block/wet_sponge",
    "minecraft:item/white_carpet": "minecraft:block/white_carpet",
    "minecraft:item/white_concrete": "minecraft:block/white_concrete",
    "minecraft:item/white_concrete_powder": "minecraft:block/white_concrete_powder",
    "minecraft:item/white_glazed_terracotta": "minecraft:block/white_glazed_terracotta",
    "minecraft:item/white_stained_glass": "minecraft:block/white_stained_glass",
    "minecraft:item/white_terracotta": "minecraft:block/white_terracotta",
    "minecraft:item/white_wool": "minecraft:block/white_wool",
    "minecraft:item/yellow_carpet": "minecraft:block/yellow_carpet",
    "minecraft:item/yellow_concrete": "minecraft:block/yellow_concrete",
    "minecraft:item/yellow_concrete_powder": "minecraft:block/yellow_concrete_powder",
    "minecraft:item/yellow_glazed_terracotta": "minecraft:block/yellow_glazed_terracotta",
    "minecraft:item/yellow_stained_glass": "minecraft:block/yellow_stained_glass",
    "minecraft:item/yellow_terracotta": "minecraft:block/yellow_terracotta",
    "minecraft:item/yellow_wool": "minecraft:block/yellow_wool"
}


